Fixed broken symlink & added icudtl.dat download
go-flutter-desktop/go-flutter pull request #33
Opened 2018-11-27 20:08 UTC by zephylac

2018-11-27 20:51 UTC, zephylac commented
Pull request not working well, check from commit : 9e4473a

2018-11-28 15:14 UTC, zephylac commented
Now it should work, fixed broken symlink on MacOS, displayed export message at the end and moved icudtl.dat file in same directory as main.go

2018-11-28 16:49 UTC, pchampio requested changes
Very useful!

2018-11-28 16:49 UTC, pchampio approved these changes

2018-11-28 16:50 UTC, merged