Feature/mac os shortcuts
go-flutter-desktop/go-flutter pull request #65
Opened 2019-01-23 22:03 UTC by zephylac

This feature add support for Mac.
Before this the modifier key was Control even on MacOS. 
With this fix, windows and linux will have Control as modifierKey whereas MacOS will have cmd which is more natural.

I decided to not add this to the configuration file because we wouldn't be compatible to each architecture or we would need to add modifier key for each platform.

I'm up for any suggestion to improve this.

2019-01-23 22:18 UTC, Drakirus commented on text_model.go
> +	if mods == ModShiftControl || mods == modifierKey {
Regression

2019-01-23 22:19 UTC, Drakirus commented on text_model.go
> +	if mods == ModShiftControl || mods == modifierKey {
Regression

2019-01-23 22:26 UTC, pchampio submitted a review, later dismissed
`ModShiftControl` is still hard coded.
Since the `modifierKey` is not necessarily `Control`, the change must take into account the new `modifierKey` in some statements.

It might me the time to move away from passing `int(mods)` into each `state` functions.
I would rather have a Boolean saying which modifier is active or not.
i.e.`state.MoveCursorLeft(true, false)` for CursorLeft + shift + no-ctrl/meta

2019-01-29 11:33 UTC, Drakirus commented
https://transfer.sh/u2ct3/flutter.gif

Regression:  ctrl-Left/Right isn't working anymore.
Regression: when the key Left is pressed it send the cursor to the start of the input.

2019-01-29 11:33 UTC, pchampio requested changes
https://transfer.sh/u2ct3/flutter.gif

Regression:  ctrl-Left/Right isn't working anymore.
Regression: when the key Left is pressed it send the cursor to the start of the input.

2019-02-19 10:12 UTC, GeertJohan commented
Have the regressions been resolved?

2019-02-19 10:29 UTC, GeertJohan commented
I think using runtime.GOOS is good as well. I'll test this PR tomorow evening on linux.

2019-02-20 23:08 UTC, GeertJohan commented
I've just merged master into this branch to make it compile again with the moved repo.

I did some testing. This still is this case on my linux machine:
> Regression: ctrl-Left/Right isn't working anymore.

The other regression has indeed been solved for linux.

2019-02-21 14:48 UTC, zephylac commented
I'll try to look into it ASAP

2019-03-04 17:56 UTC, merged